### PR TITLE
feat: react native task

### PR DESCRIPTION
**Pull request by Martian2Lee**

### CODE REVIEW

**Comment by devypt** [comment]
I think it's better to make the task e-commerce oriented, we can ask candidates to utilize https://fakestoreapi.com/ and build simple app a around it.
Also, we need to require write testing.

**Comment by meabed** [comment]
Yes as well as / more into mobile features such as push notification and deep linking

**Comment by Martian2Lee** [comment]
Hi @meabed @devypt , could we merge this version for now? Based on the feedback from candidates, we can update. Thanks for your input.

**Comment by devypt** [comment]
I don't think we should leave this to depend on candidates feedback, also the current challenge is very basic. Let's work on different one.

**Comment by Martian2Lee** [comment]
Hi @meabed @devypt , I have created a new task. Please review again. Thanks for your feedback.

**Review by devypt — APPROVED** [review]

**Pull request merged**
